CREATE TABLE `persons`(
	`Id`int(10) UNSIGNED NULL DEFAULT NULL,
    `FirstName` VARCHAR(50) NULL DEFAULT NULL,
    `LastName` VARCHAR(50) NULL DEFAULT NULL,
    `Address` VARCHAR(50) NULL DEFAULT NULL,
    `Gender` VARCHAR(50) NULL DEFAULT NULL
)
ENGINE=InnoDB
;

Alter table Persons change ID ID INT(10) auto_increment PRIMARY KEY;